/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.DateFormatSymbols;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.Vector;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import entity.BangLuongCongNhan;
import gui.GUI_APP;

/**
 *
 * @author Vu
 */
public class LuongCongNhan extends javax.swing.JPanel {
	private DefaultTableModel modelBLCN;
	public GUI_APP app;
    /**
     * Creates new form LuongCongNhan
     */
    public LuongCongNhan() {
        initComponents();
    }
  	//load bảng lương
  	private void loadBangLuong() {
  	// Tạo một đối tượng NumberFormat với Locale là Vietnamese
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("vi", "VN"));
//  		String nam = cmbNam.getSelectedItem().toString();
  		String thang = cmbThang.getSelectedItem().toString();
//  		ArrayList<BangLuongCongNhan> list = bangLuongCongNhan_dao.layBangLuongTheoThangNam(Integer.parseInt(nam), Integer.parseInt(thang));
//  		if(list.isEmpty()) {
//  			JOptionPane.showMessageDialog(null, "Tháng/năm đã chọn không có dữ liệu để tính lương");
//  		}else {
//  			for(BangLuongCongNhan luong : list) {
//  	  			modelBLCN.addRow(new Object[] {list.indexOf(luong)+1, 
//  	  					luong.getMaBangLuongCongNhan(),
//  	  					luong.getCongNhan().getMaNhanSu(),
//  	  					luong.getCongNhan().getHo() + " " + luong.getCongNhan().getTen(),
//  	  					luong.getCongNhan().getChuyenMon().getTenChuyenMon(),
//  	  					luong.getSoLuongSanPham(),
//  	  					currencyFormat.format((Double)luong.getLuongTheoSanPham()),
//  	  					currencyFormat.format(Double.parseDouble((luong.getCongNhan().getPhuCap().toString()))),
//
////  	  					luong.getCongNhan().getPhuCap(),
//  	  					currencyFormat.format((Double)luong.getTongLuong()),
//  	  					luong.getNgayLap()
//  	  					
//  	  			});
//  	  		}
//  			btnXemChiTiet.setEnabled(true);
//  			btnInBangLuong.setEnabled(true);
//  		}
  		
  		//bangLuongCongNhan_dao.layBangLuongTheoMaCongNhanVaThang(Integer.parseInt(thang));
  		ArrayList<Vector<String>> list = null;
  		int i=0;
  		for(Vector<String> luong : list) {
  			luong.add(0, ++i + "");
			modelBLCN.addRow(luong);
		}
		btnXemChiTiet.setEnabled(true);
		btnInBangLuong.setEnabled(true);
  	}

  	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
<<<<<<< HEAD
     * regenerated by the Form Editor.tbl
=======
     * regenerated by the Form Editor.
>>>>>>> c03c8a7d4cb3b119741d9d464df96cafdd42e27e
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	// Lấy tháng hiện tại từ Calendar
        Calendar calendar = Calendar.getInstance();
        int currentMonth = calendar.get(Calendar.MONTH);
     // Lấy năm hiện tại từ Calendar
        int currentYear = calendar.get(Calendar.YEAR);
     // Tạo một mảng chứa số tháng từ 1 đến 12
        String[] monthNames = new String[12];
        for (int i = 0; i < 12; i++) {
            monthNames[i] = String.valueOf(i + 1);
        }
    	
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangLuongCongNhan = new javax.swing.JTable();
        btnInBangLuong = new javax.swing.JButton();
        btnXemChiTiet = new javax.swing.JButton();
        btnTinhLuong = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbThang = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cmbNam = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(1295, 634));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bảng lương công nhân", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblBangLuongCongNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã bảng lương","Mã công nhân", "Tên công nhân", "Chuyên môn","Số lượng hoàn thành" ,"Lương theo sản phẩm (VNĐ)", "Phụ cấp (VNĐ)", "Tổng lương (VNĐ)", "Ngày lập"
            }
        ));
        
        String[] colsBLCN = {"STT","Mã bảng lương","Mã công nhân", "Tên công nhân","Chuyên môn", "Số lượng hoàn thành" ,"Lương theo sản phẩm", "Phụ cấp", "Tổng lương (VNĐ)", "Ngày lập"};
		modelBLCN = new DefaultTableModel(colsBLCN, 0);
		tblBangLuongCongNhan = new JTable(modelBLCN);
        jScrollPane1.setViewportView(tblBangLuongCongNhan);

        btnInBangLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnInBangLuong.setText("In bảng lương");
        btnInBangLuong.setEnabled(false);
        btnInBangLuong.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				InBangLuongCongNhan inBangLuongCN = new InBangLuongCongNhan(app, true, tblBangLuongCongNhan);
				inBangLuongCN.setLocationRelativeTo(null);
				inBangLuongCN.setTitle("In bảng lương công nhân");
				inBangLuongCN.setVisible(true);
			}
		});
        
        //Xem Chi Tiết
        btnXemChiTiet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXemChiTiet.setText("Xem chi tiết");
        btnXemChiTiet.setEnabled(false);
        
        btnXemChiTiet.addActionListener(new ActionListener() {			
			@Override
			public void actionPerformed(ActionEvent e) {
				if(tblBangLuongCongNhan.getSelectedRow()<0) {
					JOptionPane.showMessageDialog(null, "Vui lòng chọn công nhân cần xem chi tiết");
				}else {
					int selectedRow = tblBangLuongCongNhan.getSelectedRow();
					String maCongNhan = (String) tblBangLuongCongNhan.getValueAt(selectedRow, 2);
//					SimpleDateFormat spf = new SimpleDateFormat("yyyy-MM-dd");
					ChiTietLuongCongNhan chiTietLuongCN = null;
					chiTietLuongCN = new ChiTietLuongCongNhan(app, maCongNhan, new Date());
					chiTietLuongCN.setLocationRelativeTo(null);
					chiTietLuongCN.setVisible(true);
				}
				
			}
		});
        
        
        
        btnTinhLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTinhLuong.setText("Tính lương");
        btnTinhLuong.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				modelBLCN.setRowCount(0);
				loadBangLuong();
				
			}
		});
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel9.setText("Quản lý lương công nhân");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hệ số lương theo chuyên môn"));

        jLabel10.setText("Cắt gỗ:");

        jLabel11.setText("1.02");

        jLabel12.setText("Chế tác:");

        jLabel13.setText("1.04");

        jLabel14.setText("Lắp ráp:");

        jLabel15.setText("Bề mặt:");

        jLabel16.setText("1.0");

        jLabel17.setText("1.01");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addContainerGap(12, Short.MAX_VALUE))
        );



        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Tháng:");

        cmbThang.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbThang.setModel(new javax.swing.DefaultComboBoxModel<>(monthNames));
        cmbThang.setSelectedIndex(currentMonth);
        
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Năm:");

        
        

        // Tạo một mảng chứa số năm từ (currentYear - 10) đến (currentYear + 10)
        String[] yearNames = new String[16];
        for (int i = 0; i < 16; i++) {
            yearNames[i] = String.valueOf(currentYear - 5 + i);
        }
        cmbNam.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbNam.setModel(new javax.swing.DefaultComboBoxModel<>(yearNames));
        cmbNam.setSelectedItem(String.valueOf(currentYear));
        
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbThang, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnTinhLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(btnXemChiTiet)
                        .addGap(86, 86, 86)
                        .addComponent(btnInBangLuong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(484, 484, 484))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(cmbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInBangLuong)
                            .addComponent(btnXemChiTiet)
                            .addComponent(btnTinhLuong))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatBaoCaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatBaoCaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInBangLuong;
    private javax.swing.JButton btnTinhLuong;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JComboBox<String> cmbNam;
    private javax.swing.JComboBox<String> cmbThang;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBangLuongCongNhan;
    // End of variables declaration//GEN-END:variables
}
